### PR TITLE
Intentionally failing build to ...

### PR DESCRIPTION
**Pull request by carlschroedl**
demonstrate travis pull request integration. Real failures would happen in the java files.

### CODE REVIEW

**Comment by carlschroedl** [comment]
Please don't merge this, it's just a demonstration.

**Comment by carlschroedl** [comment]
@happyjack27, check out the red X and green checks. You can click on them to see the build output on travis.

**Comment by happyjack27** [comment]
ummm.. it looks like it says it passed...
https://travis-ci.org/happyjack27/autoredistrict/builds/105687033
did you confirm failure?

**Comment by carlschroedl** [comment]
fail-and-pass-with
I forgot how easy it is to gloss over those build badges. It must be doubly hard if you're new to github.

**Comment by happyjack27** [comment]
Got it.  Thanks.

**Pull request closed without merging**
